//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue or Address.
        /// </summary>
        public static string FlyerContactDetailsModel_Address_FlyerContactDetailsModel_Address {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_Address_FlyerContactDetailsModel_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string FlyerContactDetailsModel_EmailAddress_FlyerContactDetailsModel_EmailAddress {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_EmailAddress_FlyerContactDetailsModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FlyerContactDetailsModel_FirstName_FlyerContactDetailsModel_FirstName {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_FirstName_FlyerContactDetailsModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIddle Names.
        /// </summary>
        public static string FlyerContactDetailsModel_MiddleNames_FlyerContactDetailsModel_MiddleNames {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_MiddleNames_FlyerContactDetailsModel_MiddleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string FlyerContactDetailsModel_PhoneNumber_FlyerContactDetailsModel_PhoneNumber {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_PhoneNumber_FlyerContactDetailsModel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlyerContactDetailsModel_Surname.
        /// </summary>
        public static string FlyerContactDetailsModel_Surname_FlyerContactDetailsModel_Surname {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_Surname_FlyerContactDetailsModel_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Link.
        /// </summary>
        public static string FlyerContactDetailsModel_WebSite_FlyerContactDetailsModel_WebSite {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_WebSite_FlyerContactDetailsModel_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string ProfileEditModel_AvatarImageId_Profile_Picture {
            get {
                return ResourceManager.GetString("ProfileEditModel_AvatarImageId_Profile_Picture", resourceCulture);
            }
        }
    }
}
