//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Azure.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.Azure.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if not Exists(select * from sys.columns where Name = N&apos;{1}&apos; and Object_ID = Object_ID(N&apos;{0}&apos;))ALTER TABLE dbo.{0} ADD {2}.
        /// </summary>
        internal static string DbAddColumn {
            get {
                return ResourceManager.GetString("DbAddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create database {0}.
        /// </summary>
        internal static string DbCreate {
            get {
                return ResourceManager.GetString("DbCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE FEDERATION {0}({1} {2} RANGE).
        /// </summary>
        internal static string DbCreateFederation {
            get {
                return ResourceManager.GetString("DbCreateFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if not Exists(select * from sys.key_constraints where Parent_Object_ID = Object_ID(N&apos;{0}&apos;) and type = &apos;PK&apos;)
        ///ALTER TABLE dbo.{0} ADD CONSTRAINT PK_{0} PRIMARY KEY 
        ///({1}).
        /// </summary>
        internal static string DbCreatePrimaryKey {
            get {
                return ResourceManager.GetString("DbCreatePrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT name FROM sys.indexes
        ///            WHERE name = N&apos;IDX_{2}_{3}&apos;)
        ///CREATE {0} {1}CLUSTERED INDEX IDX_{2}_{3} ON {2}({3});.
        /// </summary>
        internal static string DbCreateSingleColIndex {
            get {
                return ResourceManager.GetString("DbCreateSingleColIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if not Exists(select * from 
        ///    sys.spatial_indexes spat
        ///    inner join
        ///    sys.index_columns idxcol on idxcol.index_id = spat.index_id
        ///    inner join
        ///    sys.columns cols on cols.column_id = idxcol.column_id
        ///    where  cols.Object_ID = Object_ID(N&apos;{0}&apos;) and cols.name = N&apos;{1}&apos;)
        ///CREATE SPATIAL INDEX SPATIAL_{0}_{1} ON dbo.{0}({1}) 
        ///USING GEOGRAPHY_GRID 
        ///WITH( GRIDS  = ( LEVEL_1  = MEDIUM, LEVEL_2  = MEDIUM, LEVEL_3  = MEDIUM, LEVEL_4  = MEDIUM), 
        ///  CELLS_PER_OBJECT  = 16, STATISTICS_NORECOMPUTE =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DbCreateSpatialIndex {
            get {
                return ResourceManager.GetString("DbCreateSpatialIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if not Exists(select * from sys.tables where Name = N&apos;{0}&apos; and Object_ID = Object_ID(N&apos;{0}&apos;)) 
        ///create table dbo.{0}
        ///(
        ///  {1},
        ///  CONSTRAINT [PK_{0}] PRIMARY KEY CLUSTERED
        ///  ({2})
        ///  WITH (STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF)
        ///).
        /// </summary>
        internal static string DbCreateTable {
            get {
                return ResourceManager.GetString("DbCreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP FEDERATION {0}.
        /// </summary>
        internal static string DbDeleteFederation {
            get {
                return ResourceManager.GetString("DbDeleteFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from {0} where {1} = @{1}.
        /// </summary>
        internal static string DbDeleteRecord {
            get {
                return ResourceManager.GetString("DbDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if Exists(select * from sys.tables where Name = N&apos;{0}&apos; and Object_ID = Object_ID(N&apos;{0}&apos;))
        ///drop table dbo.{0}.
        /// </summary>
        internal static string DbDeleteTable {
            get {
                return ResourceManager.GetString("DbDeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop database {0}.
        /// </summary>
        internal static string DbDrop {
            get {
                return ResourceManager.GetString("DbDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER DATABASE {0} SET READ_ONLY WITH ROLLBACK IMMEDIATE;ALTER DATABASE {0} SET READ_WRITE WITH ROLLBACK IMMEDIATE;.
        /// </summary>
        internal static string DbDropConnections {
            get {
                return ResourceManager.GetString("DbDropConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(*) as Count from sys.databases where name = &apos;{0}&apos;.
        /// </summary>
        internal static string DbExists {
            get {
                return ResourceManager.GetString("DbExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEDERATED ON ({0}={1}).
        /// </summary>
        internal static string DbFederatedOn {
            get {
                return ResourceManager.GetString("DbFederatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT fed.federation_id as FederationId
        ///       , fed.name as Name
        ///       , fmd.distribution_name as DistributionName
        ///       , fmd.member_id as MemberId 
        ///       , range_low as RangeLow
        ///       , range_high as RangeHigh
        ///       , typ.name as FedTyp
        ///  FROM sys.federations fed
        ///  JOIN sys.Federation_distributions dis ON dis.federation_id = fed.federation_id
        ///  JOIN sys.federation_member_distributions fmd ON fmd.federation_id = fed.federation_id
        ///  JOIN sys.types typ ON typ.system_type_id = dis.system_type [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DbGetFederationInfo {
            get {
                return ResourceManager.GetString("DbGetFederationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from {0} where {1} = @{1}.
        /// </summary>
        internal static string DbGetRecord {
            get {
                return ResourceManager.GetString("DbGetRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(*) as Count from sys.federations where name = &apos;{0}&apos;.
        /// </summary>
        internal static string DBHasFederation {
            get {
                return ResourceManager.GetString("DBHasFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin tran
        ///if exists (select * from {0} with (updlock,serializable) where {1} = @{1} )
        ///begin
        ///   update {0} set {2}
        ///   where {1} = @{1}
        ///end
        ///else
        ///begin
        ///   insert into {0} ({3})
        ///   values ({4})
        ///end
        ///commit tran.
        /// </summary>
        internal static string DbInsertOrUpdateRecord {
            get {
                return ResourceManager.GetString("DbInsertOrUpdateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE FEDERATION {0}({1}={2}) WITH RESET, FILTERING=OFF.
        /// </summary>
        internal static string DbUseFederation {
            get {
                return ResourceManager.GetString("DbUseFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE FEDERATION ROOT WITH RESET.
        /// </summary>
        internal static string DbUseFederationRoot {
            get {
                return ResourceManager.GetString("DbUseFederationRoot", resourceCulture);
            }
        }
    }
}
