//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostaFlya.DataRepository.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PostaFlya.DataRepository.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindFliersByLocationAndTags2.
        /// </summary>
        internal static string SqlAllOrderedBy {
            get {
                return ResourceManager.GetString("SqlAllOrderedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindFliersByBoard2.
        /// </summary>
        internal static string SqlSeachFliersByBoard {
            get {
                return ResourceManager.GetString("SqlSeachFliersByBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindFlyersByDateRange.
        /// </summary>
        internal static string SqlSeachFlyersByDate {
            get {
                return ResourceManager.GetString("SqlSeachFlyersByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindFliersByLocationAndTags2.
        /// </summary>
        internal static string SqlSearchFliersByLocationTags {
            get {
                return ResourceManager.GetString("SqlSearchFliersByLocationTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindFlyersByByBoardAndDate.
        /// </summary>
        internal static string SqlSearchFlyersByByBoardAndDate {
            get {
                return ResourceManager.GetString("SqlSearchFlyersByByBoardAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--CONTEXT=PostaFlya.DataRepository.Search.SearchRecord.FlierSearchRecord
        ///if not exists (select * from sys.objects where type = &apos;P&apos; AND name = &apos;FindFliersByLocationAndTags2&apos;)
        ///   exec(&apos;create procedure FindFliersByLocationAndTags2 as begin SET NOCOUNT ON; end&apos;)
        ///GO
        ///	
        ///--CONTEXT=PostaFlya.DataRepository.Search.SearchRecord.FlierSearchRecord 
        ///alter procedure FindFliersByLocationAndTags2
        ///	@loc geography,
        ///	@top int,
        ///	@distance int,
        ///	@sort int = 1,
        ///	@skipPast bigint = null,
        ///	@skipPastEventAndCreateDate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoredProcs {
            get {
                return ResourceManager.GetString("StoredProcs", resourceCulture);
            }
        }
    }
}
