//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostaFlya.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PostaFlya.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can consist of &apos;a-z&apos; and &apos;-&apos; only.
        /// </summary>
        public static string AlpaNumericAndHiphensOnly {
            get {
                return ResourceManager.GetString("AlpaNumericAndHiphensOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location from device.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetLocationSourceDesc_LocationFromDevice {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetLocationSourceDesc_LocationFromDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location from search.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetLocationSourceDesc_LocationFromSearch {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetLocationSourceDesc_LocationFromSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not known.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetLocationSourceDesc_LocationNotKnown {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetLocationSourceDesc_LocationNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Api.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetSourceDescription_IdByApi {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetSourceDescription_IdByApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Navigation directly to Url.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetSourceDescription_IdByBulletin {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetSourceDescription_IdByBulletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From browser location detection.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetSourceDescription_LocationTrack {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetSourceDescription_LocationTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Qr Code without poster.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetSourceDescription_QrCodeSrcCodeOnly {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetSourceDescription_QrCodeSrcCodeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Qr Code on printed flya without tear offs.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetSourceDescription_QrCodeSrcOnFlierWithoutTearOffs {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetSourceDescription_QrCodeSrcOnFlierWithoutTea" +
                        "rOffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From large Qr Code on printed flier with tear offs.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetSourceDescription_QrCodeSrcOnFlierWithTearOffs {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetSourceDescription_QrCodeSrcOnFlierWithTearOf" +
                        "fs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Qr Code on tear off tag.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetSourceDescription_QrCodeSrcTearOff {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetSourceDescription_QrCodeSrcTearOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Tiny Url typed in.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetSourceDescription_TinyUrl {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetSourceDescription_TinyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Tiny Url by Api.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetSourceDescription_TinyUrlByApi {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetSourceDescription_TinyUrlByApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string AnalyticTrackingSummaryExtensions_GetSourceDescription_Unknown {
            get {
                return ResourceManager.GetString("AnalyticTrackingSummaryExtensions_GetSourceDescription_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachContactDetails.
        /// </summary>
        public static string AttachContactDetails {
            get {
                return ResourceManager.GetString("AttachContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BehaviourType.
        /// </summary>
        public static string BehaviourType {
            get {
                return ResourceManager.GetString("BehaviourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BidAmount.
        /// </summary>
        public static string BidAmount {
            get {
                return ResourceManager.GetString("BidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowOthersToPostFliers.
        /// </summary>
        public static string BoardCreateEditModel_AllowOthersToPostFliers {
            get {
                return ResourceManager.GetString("BoardCreateEditModel_AllowOthersToPostFliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardName.
        /// </summary>
        public static string BoardCreateEditModel_BoardName {
            get {
                return ResourceManager.GetString("BoardCreateEditModel_BoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardDescription.
        /// </summary>
        public static string BoardCreateEditModel_Description {
            get {
                return ResourceManager.GetString("BoardCreateEditModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string BoardCreateEditModel_Location {
            get {
                return ResourceManager.GetString("BoardCreateEditModel_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PercentageOfPublicFliersToShow.
        /// </summary>
        public static string BoardCreateEditModel_PercentageOfPublicFliersToShow {
            get {
                return ResourceManager.GetString("BoardCreateEditModel_PercentageOfPublicFliersToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireApprovalOfPostedFliers.
        /// </summary>
        public static string BoardCreateEditModel_RequireApprovalOfPostedFliers {
            get {
                return ResourceManager.GetString("BoardCreateEditModel_RequireApprovalOfPostedFliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string BoardCreateEditModel_Status {
            get {
                return ResourceManager.GetString("BoardCreateEditModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Type.
        /// </summary>
        public static string BoardCreateEditModel_TypeOfBoard {
            get {
                return ResourceManager.GetString("BoardCreateEditModel_TypeOfBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardFlier.
        /// </summary>
        public static string BoardFlier {
            get {
                return ResourceManager.GetString("BoardFlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardId.
        /// </summary>
        public static string BoardId {
            get {
                return ResourceManager.GetString("BoardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardList.
        /// </summary>
        public static string BoardList {
            get {
                return ResourceManager.GetString("BoardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Links.
        /// </summary>
        public static string BulletinFlierModel_UserLinks_UserLinks {
            get {
                return ResourceManager.GetString("BulletinFlierModel_UserLinks_UserLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimTime.
        /// </summary>
        public static string ClaimTime {
            get {
                return ResourceManager.GetString("ClaimTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommentTime.
        /// </summary>
        public static string CommentTime {
            get {
                return ResourceManager.GetString("CommentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ContactDetailsModel_Address {
            get {
                return ResourceManager.GetString("ContactDetailsModel_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAddress.
        /// </summary>
        public static string ContactDetailsModel_EmailAddress {
            get {
                return ResourceManager.GetString("ContactDetailsModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string ContactDetailsModel_FirstName {
            get {
                return ResourceManager.GetString("ContactDetailsModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiddleNames.
        /// </summary>
        public static string ContactDetailsModel_MiddleNames {
            get {
                return ResourceManager.GetString("ContactDetailsModel_MiddleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string ContactDetailsModel_PhoneNumber {
            get {
                return ResourceManager.GetString("ContactDetailsModel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ContactDetailsModel_Surname {
            get {
                return ResourceManager.GetString("ContactDetailsModel_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string ContactDetailsModel_WebSite {
            get {
                return ResourceManager.GetString("ContactDetailsModel_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostOverhead.
        /// </summary>
        public static string CostOverhead {
            get {
                return ResourceManager.GetString("CostOverhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostOverheadDisplay.
        /// </summary>
        public static string CostOverheadDisplay {
            get {
                return ResourceManager.GetString("CostOverheadDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryName.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flya Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraLocations.
        /// </summary>
        public static string ExtraLocations {
            get {
                return ResourceManager.GetString("ExtraLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial source.
        /// </summary>
        public static string FlierAnalyticTrackingSummaryModel_InitialSource {
            get {
                return ResourceManager.GetString("FlierAnalyticTrackingSummaryModel_InitialSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial visit time.
        /// </summary>
        public static string FlierAnalyticTrackingSummaryModel_InitialVisitTime {
            get {
                return ResourceManager.GetString("FlierAnalyticTrackingSummaryModel_InitialVisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Location.
        /// </summary>
        public static string FlierAnalyticTrackingSummaryModel_Location {
            get {
                return ResourceManager.GetString("FlierAnalyticTrackingSummaryModel_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location source.
        /// </summary>
        public static string FlierAnalyticTrackingSummaryModel_LocationSource {
            get {
                return ResourceManager.GetString("FlierAnalyticTrackingSummaryModel_LocationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of views from this Tracking Id.
        /// </summary>
        public static string FlierAnalyticTrackingSummaryModel_TotalDetailViews {
            get {
                return ResourceManager.GetString("FlierAnalyticTrackingSummaryModel_TotalDetailViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Tracking Id.
        /// </summary>
        public static string FlierAnalyticTrackingSummaryModel_TrackingId_TrackingId {
            get {
                return ResourceManager.GetString("FlierAnalyticTrackingSummaryModel_TrackingId_TrackingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User agent (browser and or device) information .
        /// </summary>
        public static string FlierAnalyticTrackingSummaryModel_UserAgent {
            get {
                return ResourceManager.GetString("FlierAnalyticTrackingSummaryModel_UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Specified Contact Details.
        /// </summary>
        public static string FlierCreateModel_AttachSuppliedContactDetails {
            get {
                return ResourceManager.GetString("FlierCreateModel_AttachSuppliedContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Contact Details to Flier.
        /// </summary>
        public static string FlierCreateModel_AttachTearOffs {
            get {
                return ResourceManager.GetString("FlierCreateModel_AttachTearOffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Analytics for flier.
        /// </summary>
        public static string FlierCreateModel_EnableAnalytics_EnableAnalytics {
            get {
                return ResourceManager.GetString("FlierCreateModel_EnableAnalytics_EnableAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostLocationRadius.
        /// </summary>
        public static string FlierCreateModel_PostRadius {
            get {
                return ResourceManager.GetString("FlierCreateModel_PostRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlierDescription.
        /// </summary>
        public static string FlierDescription {
            get {
                return ResourceManager.GetString("FlierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlierId.
        /// </summary>
        public static string FlierId {
            get {
                return ResourceManager.GetString("FlierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string FlierImage {
            get {
                return ResourceManager.GetString("FlierImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlierImages.
        /// </summary>
        public static string FlierImages {
            get {
                return ResourceManager.GetString("FlierImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlierLocation.
        /// </summary>
        public static string FlierLocation {
            get {
                return ResourceManager.GetString("FlierLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string FlierStatus {
            get {
                return ResourceManager.GetString("FlierStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flier Tags.
        /// </summary>
        public static string FlierTags {
            get {
                return ResourceManager.GetString("FlierTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flier Title.
        /// </summary>
        public static string FlierTitle {
            get {
                return ResourceManager.GetString("FlierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is and invalid Id.
        /// </summary>
        public static string FlierTitleRequired {
            get {
                return ResourceManager.GetString("FlierTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string FlyerContactDetailsModel_Address_FlyerContactDetailsModel_Address_FlyerContactDetailsModel_Address {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_Address_FlyerContactDetailsModel_Address_FlyerContactDet" +
                        "ailsModel_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string FlyerContactDetailsModel_EmailAddress_FlyerContactDetailsModel_EmailAddress_FlyerContactDetailsModel_EmailAddress {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_EmailAddress_FlyerContactDetailsModel_EmailAddress_Flyer" +
                        "ContactDetailsModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FlyerContactDetailsModel_FirstName_FlyerContactDetailsModel_FirstName_FlyerContactDetailsModel_FirstName {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_FirstName_FlyerContactDetailsModel_FirstName_FlyerContac" +
                        "tDetailsModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Names.
        /// </summary>
        public static string FlyerContactDetailsModel_MiddleNames_FlyerContactDetailsModel_MiddleNames_FlyerContactDetailsModel_MiddleNames {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_MiddleNames_FlyerContactDetailsModel_MiddleNames_FlyerCo" +
                        "ntactDetailsModel_MiddleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string FlyerContactDetailsModel_PhoneNumber_FlyerContactDetailsModel_PhoneNumber_FlyerContactDetailsModel_PhoneNumber {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_PhoneNumber_FlyerContactDetailsModel_PhoneNumber_FlyerCo" +
                        "ntactDetailsModel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string FlyerContactDetailsModel_Surname_FlyerContactDetailsModel_Surname_FlyerContactDetailsModel_Surname {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_Surname_FlyerContactDetailsModel_Surname_FlyerContactDet" +
                        "ailsModel_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Link.
        /// </summary>
        public static string FlyerContactDetailsModel_WebSite_FlyerContactDetailsModel_WebSite_FlyerContactDetailsModel_WebSite {
            get {
                return ResourceManager.GetString("FlyerContactDetailsModel_WebSite_FlyerContactDetailsModel_WebSite_FlyerContactDet" +
                        "ailsModel_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FriendlyId.
        /// </summary>
        public static string FriendlyId {
            get {
                return ResourceManager.GetString("FriendlyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle.
        /// </summary>
        public static string Handle {
            get {
                return ResourceManager.GetString("Handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageProcessing {
            get {
                object obj = ResourceManager.GetObject("ImageProcessing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageProcessingFailed {
            get {
                object obj = ResourceManager.GetObject("ImageProcessingFailed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageTitle.
        /// </summary>
        public static string ImageTitle {
            get {
                return ResourceManager.GetString("ImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid email address..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is and invalid Id.
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxTaskAmount.
        /// </summary>
        public static string MaxTaskAmount {
            get {
                return ResourceManager.GetString("MaxTaskAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NotFoundImg {
            get {
                object obj = ResourceManager.GetObject("NotFoundImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfClaims.
        /// </summary>
        public static string NumberOfClaims {
            get {
                return ResourceManager.GetString("NumberOfClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfComments.
        /// </summary>
        public static string NumberOfComments {
            get {
                return ResourceManager.GetString("NumberOfComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}.
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaceName.
        /// </summary>
        public static string PlaceName {
            get {
                return ResourceManager.GetString("PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostCode.
        /// </summary>
        public static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetAddress.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreetNumber.
        /// </summary>
        public static string StreetNumber {
            get {
                return ResourceManager.GetString("StreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1} characters.
        /// </summary>
        public static string StringTooLarge {
            get {
                return ResourceManager.GetString("StringTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {2} and {1} characters.
        /// </summary>
        public static string StringTooLargeOrSmall {
            get {
                return ResourceManager.GetString("StringTooLargeOrSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagList.
        /// </summary>
        public static string TagList {
            get {
                return ResourceManager.GetString("TagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Url.
        /// </summary>
        public static string UserLinkViewModel_Link_Link_Url {
            get {
                return ResourceManager.GetString("UserLinkViewModel_Link_Link_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Text.
        /// </summary>
        public static string UserLinkViewModel_Text_Link_Text {
            get {
                return ResourceManager.GetString("UserLinkViewModel_Text_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Type.
        /// </summary>
        public static string UserLinkViewModel_Type_Link_Type {
            get {
                return ResourceManager.GetString("UserLinkViewModel_Type_Link_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid location.
        /// </summary>
        public static string ValidLocation {
            get {
                return ResourceManager.GetString("ValidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid website address..
        /// </summary>
        public static string ValidUrl {
            get {
                return ResourceManager.GetString("ValidUrl", resourceCulture);
            }
        }
    }
}
