namespace TravelSite.Applications.Intergrations.Expedia
{
    public enum ExpediaPropertyFields
    {
        EANHotelId,
        SequenceNumber,
        Name,
        Address1,
        Address2,
        City,
        StateProvince,
        PostalCode,
        Country,
        Latitude,
        Longitude,
        AirportCode,
        PropertyCategory,
        PropertyCurrency,
        StarRating,
        Confidence,
        SupplierType,
        Location,
        ChainCodeId,
        RegionId,
        HighRate,
        LowRate,
        CheckInTime,
        CheckOutTime
    }
}