//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Azure.Common.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.Azure.Common.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///--- OrderAggregateTable --------------------------------------------------------------------------------
        ///if not exists (select * from sysobjects where name=&apos;OrderAggregateTable&apos; and xtype=&apos;U&apos;)
        ///begin
        ///
        ///create table OrderAggregateTable (
        ///    Id nvarchar(256) CONSTRAINT OrderAggregateTable_Id UNIQUE NONCLUSTERED not null,
        ///    FriendlyId nvarchar(512) CONSTRAINT OrderAggregateTable_Id UNIQUE NONCLUSTERED not null,
        ///	RowId bigint IDENTITY PRIMARY KEY,
        ///	ShardId bigint,
        ///
        ///	Json nvarchar(MAX),
        ///	JsonHash [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderAggregateTable_create_table {
            get {
                return ResourceManager.GetString("OrderAggregateTable_create_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///if exists (select * from sysobjects where name=&apos;OrderAggregateTable&apos; and xtype=&apos;U&apos;)
        ///begin
        ///	truncate table OrderAggregateTable
        ///	drop table OrderAggregateTable
        ///end
        ///GO
        ///
        ///
        ///.
        /// </summary>
        internal static string OrderAggregateTable_drop_table {
            get {
                return ResourceManager.GetString("OrderAggregateTable_drop_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- OrderLineItemRootMemberTable --------------------------------------------------------------------------------
        ///if not exists (select * from sysobjects where name=&apos;OrderLineItemRootMemberTable&apos; and xtype=&apos;U&apos;)
        ///begin
        ///
        ///create table OrderLineItemRootMemberTable (
        ///    Id nvarchar(256) not null,
        ///	RowId bigint IDENTITY PRIMARY KEY,
        ///	ShardId bigint,
        ///
        ///	ProductId nvarchar(256) NOT NULL,
        ///	Price decimal(18, 2) NULL,
        ///	Quantity int,
        ///	
        ///)
        ///
        ///end
        ///GO
        ///IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = &apos;I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderLineItemRootMemberTable_create_table {
            get {
                return ResourceManager.GetString("OrderLineItemRootMemberTable_create_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///if exists (select * from sysobjects where name=&apos;OrderLineItemRootMemberTable&apos; and xtype=&apos;U&apos;)
        ///begin
        ///	truncate table OrderLineItemRootMemberTable
        ///	drop table OrderLineItemRootMemberTable
        ///end
        ///GO
        ///
        ///
        ///.
        /// </summary>
        internal static string OrderLineItemRootMemberTable_drop_table {
            get {
                return ResourceManager.GetString("OrderLineItemRootMemberTable_drop_table", resourceCulture);
            }
        }
    }
}
